# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')

setup(
    long_description=readme,
    name='prometheus-sanic',
    version='1.0.0',
    description='Exposes Prometheus monitoring metrics of Sanic apps.',
    python_requires='<4.0,>=3.6',
    project_urls={'repository': 'https://github.com/skar404/prometheus-sanic'},
    author='Dan Kruchinin',
    author_email='dan.kruchinin@gmail.com',
    maintainer='skar404',
    maintainer_email='skar404@gmail.com',
    license='MIT',
    keywords='python prometheus sanic monitoring python-library',
    classifiers=[
        'Intended Audience :: Developers', 'Development Status :: 3 - Alpha',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent', 'Environment :: Web Environment',
        'Topic :: System :: Monitoring',
        'Topic :: Internet :: WWW/HTTP :: Dynamic Content',
        'Topic :: Software Development :: Libraries :: Python Modules',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7'
    ],
    packages=['prometheus_sanic'],
    package_data={},
    install_requires=['prometheus-client==0.*,>=0.7.1', 'sanic>=0.7.0'],
    extras_require={'dev': ['flake8==3.*,>=3.3.0']},
)
