name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip poetry
        poetry install
    - name: Build lib
      run: |
        source $HOME/.poetry/env
        python setup.py install
    - name: Lint with flake8
      run: |
        source $HOME/.poetry/env
        poetry run flake8 --ignore=E731 --ignore=F401 prometheus_sanic
    - name: Test with pytest
      run: |
        source $HOME/.poetry/env
        ./tests/run_multiproc_it.sh
